#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;
use ACTom\COSCmd\Command\MoveCommand;

$config = require __DIR__ . '/config.php';

$application = new Application();
$application->setName('Tencent Cloud COS Command Tool');
$application->setVersion('v0.0.1');
$application->add(new MoveCommand());
$application->run();